// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: memory_message.proto

package com.mycompany.grpc;

public final class MemoryMessage {
  private MemoryMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MemoryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.mycompany.grpc.Memory)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 value = 1;</code>
     */
    long getValue();

    /**
     * <code>.com.mycompany.grpc.Memory.Unit unit = 2;</code>
     */
    int getUnitValue();
    /**
     * <code>.com.mycompany.grpc.Memory.Unit unit = 2;</code>
     */
    com.mycompany.grpc.MemoryMessage.Memory.Unit getUnit();
  }
  /**
   * Protobuf type {@code com.mycompany.grpc.Memory}
   */
  public  static final class Memory extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.mycompany.grpc.Memory)
      MemoryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Memory.newBuilder() to construct.
    private Memory(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Memory() {
      value_ = 0L;
      unit_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Memory(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              value_ = input.readUInt64();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              unit_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mycompany.grpc.MemoryMessage.internal_static_com_mycompany_grpc_Memory_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mycompany.grpc.MemoryMessage.internal_static_com_mycompany_grpc_Memory_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mycompany.grpc.MemoryMessage.Memory.class, com.mycompany.grpc.MemoryMessage.Memory.Builder.class);
    }

    /**
     * Protobuf enum {@code com.mycompany.grpc.Memory.Unit}
     */
    public enum Unit
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN = 0;</code>
       */
      UNKNOWN(0),
      /**
       * <code>BIT = 1;</code>
       */
      BIT(1),
      /**
       * <code>BYTE = 2;</code>
       */
      BYTE(2),
      /**
       * <code>KILOBYTE = 3;</code>
       */
      KILOBYTE(3),
      /**
       * <code>MEGABYTE = 4;</code>
       */
      MEGABYTE(4),
      /**
       * <code>GIGABYTE = 5;</code>
       */
      GIGABYTE(5),
      /**
       * <code>TERABYTE = 6;</code>
       */
      TERABYTE(6),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNKNOWN = 0;</code>
       */
      public static final int UNKNOWN_VALUE = 0;
      /**
       * <code>BIT = 1;</code>
       */
      public static final int BIT_VALUE = 1;
      /**
       * <code>BYTE = 2;</code>
       */
      public static final int BYTE_VALUE = 2;
      /**
       * <code>KILOBYTE = 3;</code>
       */
      public static final int KILOBYTE_VALUE = 3;
      /**
       * <code>MEGABYTE = 4;</code>
       */
      public static final int MEGABYTE_VALUE = 4;
      /**
       * <code>GIGABYTE = 5;</code>
       */
      public static final int GIGABYTE_VALUE = 5;
      /**
       * <code>TERABYTE = 6;</code>
       */
      public static final int TERABYTE_VALUE = 6;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Unit valueOf(int value) {
        return forNumber(value);
      }

      public static Unit forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          case 1: return BIT;
          case 2: return BYTE;
          case 3: return KILOBYTE;
          case 4: return MEGABYTE;
          case 5: return GIGABYTE;
          case 6: return TERABYTE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Unit>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Unit> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Unit>() {
              public Unit findValueByNumber(int number) {
                return Unit.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.mycompany.grpc.MemoryMessage.Memory.getDescriptor().getEnumTypes().get(0);
      }

      private static final Unit[] VALUES = values();

      public static Unit valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Unit(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.mycompany.grpc.Memory.Unit)
    }

    public static final int VALUE_FIELD_NUMBER = 1;
    private long value_;
    /**
     * <code>uint64 value = 1;</code>
     */
    public long getValue() {
      return value_;
    }

    public static final int UNIT_FIELD_NUMBER = 2;
    private int unit_;
    /**
     * <code>.com.mycompany.grpc.Memory.Unit unit = 2;</code>
     */
    public int getUnitValue() {
      return unit_;
    }
    /**
     * <code>.com.mycompany.grpc.Memory.Unit unit = 2;</code>
     */
    public com.mycompany.grpc.MemoryMessage.Memory.Unit getUnit() {
      @SuppressWarnings("deprecation")
      com.mycompany.grpc.MemoryMessage.Memory.Unit result = com.mycompany.grpc.MemoryMessage.Memory.Unit.valueOf(unit_);
      return result == null ? com.mycompany.grpc.MemoryMessage.Memory.Unit.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (value_ != 0L) {
        output.writeUInt64(1, value_);
      }
      if (unit_ != com.mycompany.grpc.MemoryMessage.Memory.Unit.UNKNOWN.getNumber()) {
        output.writeEnum(2, unit_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (value_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, value_);
      }
      if (unit_ != com.mycompany.grpc.MemoryMessage.Memory.Unit.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, unit_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mycompany.grpc.MemoryMessage.Memory)) {
        return super.equals(obj);
      }
      com.mycompany.grpc.MemoryMessage.Memory other = (com.mycompany.grpc.MemoryMessage.Memory) obj;

      boolean result = true;
      result = result && (getValue()
          == other.getValue());
      result = result && unit_ == other.unit_;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getValue());
      hash = (37 * hash) + UNIT_FIELD_NUMBER;
      hash = (53 * hash) + unit_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mycompany.grpc.MemoryMessage.Memory parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mycompany.grpc.MemoryMessage.Memory parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mycompany.grpc.MemoryMessage.Memory parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mycompany.grpc.MemoryMessage.Memory parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mycompany.grpc.MemoryMessage.Memory parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mycompany.grpc.MemoryMessage.Memory parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mycompany.grpc.MemoryMessage.Memory parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mycompany.grpc.MemoryMessage.Memory parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mycompany.grpc.MemoryMessage.Memory parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.mycompany.grpc.MemoryMessage.Memory parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mycompany.grpc.MemoryMessage.Memory parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mycompany.grpc.MemoryMessage.Memory parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mycompany.grpc.MemoryMessage.Memory prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mycompany.grpc.Memory}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.mycompany.grpc.Memory)
        com.mycompany.grpc.MemoryMessage.MemoryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mycompany.grpc.MemoryMessage.internal_static_com_mycompany_grpc_Memory_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mycompany.grpc.MemoryMessage.internal_static_com_mycompany_grpc_Memory_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mycompany.grpc.MemoryMessage.Memory.class, com.mycompany.grpc.MemoryMessage.Memory.Builder.class);
      }

      // Construct using com.mycompany.grpc.MemoryMessage.Memory.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        value_ = 0L;

        unit_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mycompany.grpc.MemoryMessage.internal_static_com_mycompany_grpc_Memory_descriptor;
      }

      @java.lang.Override
      public com.mycompany.grpc.MemoryMessage.Memory getDefaultInstanceForType() {
        return com.mycompany.grpc.MemoryMessage.Memory.getDefaultInstance();
      }

      @java.lang.Override
      public com.mycompany.grpc.MemoryMessage.Memory build() {
        com.mycompany.grpc.MemoryMessage.Memory result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.mycompany.grpc.MemoryMessage.Memory buildPartial() {
        com.mycompany.grpc.MemoryMessage.Memory result = new com.mycompany.grpc.MemoryMessage.Memory(this);
        result.value_ = value_;
        result.unit_ = unit_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mycompany.grpc.MemoryMessage.Memory) {
          return mergeFrom((com.mycompany.grpc.MemoryMessage.Memory)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mycompany.grpc.MemoryMessage.Memory other) {
        if (other == com.mycompany.grpc.MemoryMessage.Memory.getDefaultInstance()) return this;
        if (other.getValue() != 0L) {
          setValue(other.getValue());
        }
        if (other.unit_ != 0) {
          setUnitValue(other.getUnitValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mycompany.grpc.MemoryMessage.Memory parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mycompany.grpc.MemoryMessage.Memory) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long value_ ;
      /**
       * <code>uint64 value = 1;</code>
       */
      public long getValue() {
        return value_;
      }
      /**
       * <code>uint64 value = 1;</code>
       */
      public Builder setValue(long value) {
        
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 value = 1;</code>
       */
      public Builder clearValue() {
        
        value_ = 0L;
        onChanged();
        return this;
      }

      private int unit_ = 0;
      /**
       * <code>.com.mycompany.grpc.Memory.Unit unit = 2;</code>
       */
      public int getUnitValue() {
        return unit_;
      }
      /**
       * <code>.com.mycompany.grpc.Memory.Unit unit = 2;</code>
       */
      public Builder setUnitValue(int value) {
        unit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.mycompany.grpc.Memory.Unit unit = 2;</code>
       */
      public com.mycompany.grpc.MemoryMessage.Memory.Unit getUnit() {
        @SuppressWarnings("deprecation")
        com.mycompany.grpc.MemoryMessage.Memory.Unit result = com.mycompany.grpc.MemoryMessage.Memory.Unit.valueOf(unit_);
        return result == null ? com.mycompany.grpc.MemoryMessage.Memory.Unit.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.mycompany.grpc.Memory.Unit unit = 2;</code>
       */
      public Builder setUnit(com.mycompany.grpc.MemoryMessage.Memory.Unit value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        unit_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.mycompany.grpc.Memory.Unit unit = 2;</code>
       */
      public Builder clearUnit() {
        
        unit_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.mycompany.grpc.Memory)
    }

    // @@protoc_insertion_point(class_scope:com.mycompany.grpc.Memory)
    private static final com.mycompany.grpc.MemoryMessage.Memory DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mycompany.grpc.MemoryMessage.Memory();
    }

    public static com.mycompany.grpc.MemoryMessage.Memory getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Memory>
        PARSER = new com.google.protobuf.AbstractParser<Memory>() {
      @java.lang.Override
      public Memory parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Memory(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Memory> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Memory> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.mycompany.grpc.MemoryMessage.Memory getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mycompany_grpc_Memory_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mycompany_grpc_Memory_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024memory_message.proto\022\022com.mycompany.gr" +
      "pc\"\246\001\n\006Memory\022\r\n\005value\030\001 \001(\004\022-\n\004unit\030\002 \001" +
      "(\0162\037.com.mycompany.grpc.Memory.Unit\"^\n\004U" +
      "nit\022\013\n\007UNKNOWN\020\000\022\007\n\003BIT\020\001\022\010\n\004BYTE\020\002\022\014\n\010K" +
      "ILOBYTE\020\003\022\014\n\010MEGABYTE\020\004\022\014\n\010GIGABYTE\020\005\022\014\n" +
      "\010TERABYTE\020\006b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_mycompany_grpc_Memory_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_mycompany_grpc_Memory_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mycompany_grpc_Memory_descriptor,
        new java.lang.String[] { "Value", "Unit", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
